export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'

export const CREATE_CART_REQUEST = "CREATE_CART_REQUEST"
export const CREATE_CART_SUCCESS = "CREATE_CART_SUCCESS"
export const CREATE_CART_FAIL = "CREATE_CART_FAIL"

export const GET_CART_REQUEST = "GET_CART_REQUEST"
export const GET_CART_SUCCESS = "GET_CART_SUCCESS"
export const GET_CART_FAIL = "GET_CART_FAIL"
export const CLOSE_CART_REQUEST = "CLOSE_CART_REQUEST"
export const CLOSE_CART_SUCCESS = "CLOSE_CART_SUCCESS"
export const CLOSE_CART_FAIL = "CLOSE_CART_FAIL"
export const EDIT_CART_REQUEST = "EDIT_CART_REQUEST"
export const EDIT_CART_SUCCESS = "EDIT_CART_SUCCESS"
export const EDIT_CART_FAIL = "EDIT_CART_FAIL"

export const GET_CATEGORIES_REQUEST = "GET_CATEGORIES_REQUEST"
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS"
export const GET_CATEGORIES_FAIL = "GET_CATEGORIES_FAIL"
export const SET_ACTIVE_CATEGORY = "SET_ACTIVE_CATEGORY"

export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST"
export const GET_PRODUCTS_SUCCESS = "SET_ACTIVE_SUCCESS"
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL"

export const GET_CART_ITEMS_REQUEST = "GET_CART_ITEMS_REQUEST"
export const GET_CART_ITEMS_SUCCESS = "GET_CART_ITEMS_SUCCESS"
export const GET_CART_ITEMS_FAIL = "GET_CART_ITEMS_FAIL"
export const ADD_CART_ITEM_REQUEST = "ADD_CART_ITEM_REQUEST"
export const ADD_CART_ITEM_SUCCESS = "ADD_CART_ITEM_SUCCESS"
export const ADD_CART_ITEM_FAIL = "ADD_CART_ITEM_FAIL"
export const REMOVE_CART_ITEM_REQUEST = "REMOVE_CART_ITEM_REQUEST"
export const REMOVE_CART_ITEM_SUCCESS = "REMOVE_CART_ITEM_SUCCESS"
export const REMOVE_CART_ITEM_FAIL = "REMOVE_CART_ITEM_FAIL"
export const UPDATE_CART_ITEM_REQUEST = "UPDATE_CART_ITEM_REQUEST"
export const UPDATE_CART_ITEM_SUCCESS = "UPDATE_CART_ITEM_SUCCESS"
export const UPDATE_CART_ITEM_FAIL = "UPDATE_CART_ITEM_FAIL"

export const GET_EMPLOYEES_REQUEST = "GET_EMPLOYEES_REQUEST"
export const GET_EMPLOYEES_SUCCESS = "GET_EMPLOYEES_SUCCESS"
export const GET_EMPLOYEES_FAIL = "GET_EMPLOYEES_FAIL"

export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST"
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS"
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL"
export const MARK_ORDER_EDITED_REQUEST = "MARK_ORDER_EDITED_REQUEST"
export const MARK_ORDER_EDITED_SUCCESS = "MARK_ORDER_EDITED_SUCCESS"
export const MARK_ORDER_EDITED_FAIL = "MARK_ORDER_EDITED_FAIL"
export const UPDATE_ORDER_REQUEST = "UPDATE_ORDER_REQUEST"
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS"
export const UPDATE_ORDER_FAIL = "UPDATE_ORDER_FAIL"
export const RESET_MESSAGE = "RESET_MESSAGE"

export const SEND_EMAIL_REQUEST = "SEND_EMAIL_REQUEST"
export const SEND_EMAIL_SUCCESS = "SEND_EMAIL_SUCCES"
export const SEND_EMAIL_FAIL = "SEND_EMAIL_FAIL"

export const GET_RECENT_ORDERS_REQUEST = "GET_RECENT_ORDERS_REQUEST"
export const GET_RECENT_ORDERS_SUCCESS = "GET_RECENT_ORDERS_SUCCESS"
export const GET_RECENT_ORDERS_FAIL = "GET_RECENT_ORDERS_FAIL"


